name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Set this to your default branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
    # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      # Navigate to Flutter project directory and get dependencies
      - name: Get dependencies
        working-directory: ./githubpages
        run: flutter pub get

        
      
      # Build Flutter web in the correct directory
      - name: Build Flutter web
        working-directory: ./githubpages
        run: flutter build web
      
      # Copy build files to parent directory (root)
      - name: Copy build files to root
        run: |
          cp -r githubpages/build/web/* ./
          rm -rf githubpages/build
       
      # Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'  # Only deploy when pushing to main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true  # Keep only the latest version of the site
